name: Run ESLint on Pull Requests

on:
  pull_request: 
    types: [opened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Super-Linter
      uses: super-linter/super-linter@v7.1.0
          

          




