name: Run ESLint on Pull Requests

on:
  pull_request: 
    types: [opened]



jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use Node.js version 14 or higher for modern syntax

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .
          
          




